FROM python:3.13-slim

WORKDIR /mlflow

COPY mlruns ./mlruns

RUN pip install mlflow

EXPOSE 5000

CMD ["mlflow", "server", "--backend-store-uri", "/mlflow/mlruns", "--artifacts-destination", "/mlflow/mlruns", "--host", "0.0.0.0", "--port", "5000", "--allowed-hosts", "*", "--cors-allowed-origins", "*"]