services:
  mlflow:
    image: yee1098/churn-mlflow:0.1.0
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns

  api:
    image: churn-api:0.1.0
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      - mlflow